### ISSUE TITLE
Error Non-static method Spatie\GoogleTagManager\GoogleTagManager::set() cannot be called statically http://localhost/

### ISSUE THREAD

**Issue by muhannadalhariri** [spatie/weight-conversions#3]
Dear Team, 
First of all, I would like to thank you for this great library. 
I have installed it and now trying to perform sample push. 

I got the following exception 

**Error
Non-static method Spatie\GoogleTagManager\GoogleTagManager::set() cannot be called statically
http://localhost/**

**Comment by freekmurze** [comment]
That is not a function provided by this package.
